# Custom values for Dagster Helm chart
dagster-user-deployments:
  enabled: true
  deployments:
    - name: "hydrosat-deployment"
      image:
        repository: "hydrosat-dagster"
        tag: "latest"
        pullPolicy: "IfNotPresent"
      dagsterApiGrpcArgs:
        - "--python-file"
        - "definitions.py"
      port: 3030
      env:
        - name: "AWS_REGION"
          value: "us-east-1"
        - name: "INPUT_BUCKET"
          value: "hydrosat-input-data"
        - name: "OUTPUT_BUCKET"
          value: "hydrosat-output-data"

postgresql:
  enabled: true
  postgresqlPassword: "dagster"

dagster:
  webserver:
    enabled: true
  daemon:
    enabled: true